### ISSUE TITLE
Occasional Server Crash on rendering items

### ISSUE THREAD

**Issue by GeekyBakerBen** [FREEDINN3R/Items-Displayed-Fabric#11]
I've started having another infrequent server crash, and the crash report seems to indicate an issue with Items Displayed.

Currently using v1.2.1, and currently have the following items from the mod placed in my base:

Spire, Coast, Eye, Sentry and Wild armor trims
Blade, Mourner, and Explorer pottery sherds
A small stack of Copper ingots
11 Display Frames

Most of the time they render without any issue, but just on occasion when rendering the items (usually the first time after I've logged on), my server crashes out (crash report attached)
[crash-2023-11-21_12.57.54-client.txt](https://github.com/FREEDINN3R/Items-Displayed-Fabric/files/13426604/crash-2023-11-21_12.57.54-client.txt)

**Comment by FREEDINN3R** [comment]
Oh jeez, not again :0
Are you still using Minecraft 1.20.1? I'll try to figure out what can be wrong as soon as I have enough time.

**Comment by GeekyBakerBen** [comment]
Yes, sorry. 1.20.1.

It's not every time, quite often it'll render the items without issue, but once in a while it'll crash me out (server doesn't need resetting, so actually I suppose it's my client crashing, not the server sorry. The crash report is always the same though, and the fact that it mentions you, I can only assume it's the rendering of objects from this mod that cause it.

No huge rush on it - for now I just put the items in storage until it's fixed. :)

**Comment by FREEDINN3R** [comment]
No need to be sorry. Yeah, it's definitely a client side thing, and it seems to be similar to what you experienced before v1.2.1. That's why I'm surprised to see it again.

**Comment by FREEDINN3R** [comment]
Okay, I did a quick fix. I don't understand completely why this error occurs, but at least your server shouldn't crash anymore.
