### ISSUE TITLE
[Request] Add block tags

### ISSUE THREAD

**Issue by CarlMichaelFabe** [FREEDINN3R/Items-Displayed-Fabric#14]
I'm using this mod https://modrinth.com/mod/fluidlogged and would like to add the placeable items to its Fluid Permeable Blocks list. 

It would be nice to be able to add all sherds using a tag like `#items_displayed:sherds`, same for the other items. At the moment, I'm only able to do so by inputting each item individually.

Thanks for the amazing mod btw <3.

**Comment by FREEDINN3R** [comment]
Hey, thanks for your suggestion, I will look into that later!
