### ISSUE TITLE
[CRASH] Getting a client render crash when placing some templates

### ISSUE THREAD

**Issue by Tempest-5ky** [FREEDINN3R/Items-Displayed-Fabric#15]
What it says on the tin, getting a crash with the following log: https://mclo.gs/6g5zHLm

**Comment by FREEDINN3R** [comment]
Same problem as #11, just wait a few days, I'll upload v1.2.2 soon

**Comment by FREEDINN3R** [comment]
v1.2.2 is on Modrinth, soon on CurseForge
