### ISSUE TITLE
when going on multiplayer everything is a waterlogged sherd

### ISSUE THREAD

**Issue by hecker-01** [FREEDINN3R/Items-Displayed-Fabric#2]

**Comment by hecker-01** [comment]
I'll add some screenshots soon

**Comment by FREEDINN3R** [comment]
Please elaborate so I could fix this issue quicker

**Comment by hecker-01** [comment]
I'll add the photos after my lunch

**Comment by hecker-01** [comment]
![2023-08-13_18 17 50](https://github.com/FREEDINN3R/Items-Displayed/assets/101524930/e3ff2b62-e917-4766-ba62-5ea47b59b5c7)
![2023-08-13_18 17 54](https://github.com/FREEDINN3R/Items-Displayed/assets/101524930/137b9bbe-2a78-41a5-801d-8211ba577050)
![2023-08-13_18 18 12](https://github.com/FREEDINN3R/Items-Displayed/assets/101524930/9c5789e5-aa13-4e2d-8801-8cdde7ee9252)
![2023-08-13_18 19 14](https://github.com/FREEDINN3R/Items-Displayed/assets/101524930/2a36073f-b436-4f08-add8-47a9e8005a6c)
these are the screenshots

**Comment by FREEDINN3R** [comment]
Figured out the problem, this bug will be patched in v1.1
