### ISSUE TITLE
Items that won't display

### ISSUE THREAD

**Issue by Linahun** [FREEDINN3R/Items-Displayed-Fabric#20]
Yeeterite Ingot and Yeeterite Upgrade Template: https://modrinth.com/mod/yeeterite 
Gilded Netherite and Rose Gold Upgrade Templates: https://www.curseforge.com/minecraft/mc-mods/additional-additions 
Gilded Sherds: https://www.curseforge.com/minecraft/mc-mods/gilded-sherds 

Thank you!

**Comment by FREEDINN3R** [comment]
These items don't display because I haven't added support for them yet. Stay tuned for future updates.
