### ISSUE TITLE
game crashes when you try to place a modded smithing template

### ISSUE THREAD

**Issue by peow** [FREEDINN3R/Items-Displayed-Fabric#7]
the game crashes when you try to place in the ground a smithing template from a mod

![image](https://github.com/FREEDINN3R/Items-Displayed/assets/105888751/411ba2ad-39d0-403e-91b7-61a0f2d49638)

[crash-2023-10-01_00.01.54-client.txt](https://github.com/FREEDINN3R/Items-Displayed/files/12776014/crash-2023-10-01_00.01.54-client.txt)

**Comment by FREEDINN3R** [comment]
Will be fixed in v1.2 (probably)

**Comment by Tempest-5ky** [comment]
Seems to still be an issue, still getting the crash
https://mclo.gs/6g5zHLm
