### ISSUE TITLE
New update to v1.2 - When trying to render pre-existing placed items, server crashes

### ISSUE THREAD

**Issue by GeekyBakerBen** [FREEDINN3R/Items-Displayed-Fabric#9]
I've just updated to the new 1.2 version of Items Displayed on my multiplayer server (1.20.1 Java edition), and had several smithing templates already displayed on a shelf. As soon as they're meant to come into view and render (I can literally look at the floor and it's fine, but the moment I try to move my camera to look at them), my server crashes with the following message:

> The game crashed whilst rendering entity in world
> Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_8389()" because the return value of "net.freedinner.items_displayed.util.BlockItemMapper.getBlockOrNull(net.minecraft.class_1792, boolean)" is null

_I cannot recall off the top of my head which of the templates I had out (I think I had about 4, including coast... I'll check the others)._ EDIT - Just checked and I have Coast, Wild, Eye, and Spire on display, plus a few empty holders.

_Will try rolling back to previous version of Items Displayed._ EDIT - Have just rolled back to v1.1 and it works again fine, so there is definitely something breaking in updating to 1.2 for existing items on display...

Also to note - I did test the "new" placing down of diamonds too. It allowed me to place a single diamond block down without issue, but wouldn't let me stack any more than that single one on that same space. Previous ingots work fine though.

I do have a full crash report to offer, but not sure what best format or way to share that for you.

**Comment by FREEDINN3R** [comment]
Thank you for your report, I will try to recreate it a little later.
Are you sure you're trying to stack the diamonds without holding down Shift? The way it works, you need to hold shift only while placing an item. When trying to stack more items, you don't need to be sneaking.

**Comment by GeekyBakerBen** [comment]
> Thank you for your report, I will try to recreate it a little later.

Let me know if there's any extra information I can provide. Really love the visuals in this mod, so thank you so much!

> Are you sure you're trying to stack the diamonds without holding down Shift? The way it works, you need to hold shift only while placing an item. When trying to stack more items, you don't need to be sneaking.

I did wonder that, but I'm sure I tried both methods and sneaking OR not sneaking didn't seem to make any difference. Maybe I just missed it though, so I can re-test that once the crashing issue is resolved and I'll move back to the latest version again.

**Comment by FREEDINN3R** [comment]
Hey, so I found out why Item Display crashes your server, and I'll try to fix it as soon as possible.
However, I wasn't able to recreate the issue you had with Diamonds. Could you please provide more information later?

**Comment by GeekyBakerBen** [comment]
> Hey, so I found out why Item Display crashes your server, and I'll try to fix it as soon as possible. However, I wasn't able to recreate the issue you had with Diamonds. Could you please provide more information later?

That sounds good, I shall keep my eye out for the update. And yes, absolutely - once that crash issue is resolved we can close this one and I'll raise a new one if the diamond issue persists.

**Comment by FREEDINN3R** [comment]
I have just uploaded v1.2.1 which fixes the issue with rendering. It should be available on Modrinth at this point, on CurseForge it's still under moderation. Do let me know if it fixes these problems for you.

**Comment by GeekyBakerBen** [comment]
> I have just uploaded v1.2.1 which fixes the issue with rendering. It should be available on Modrinth at this point, on CurseForge it's still under moderation. Do let me know if it fixes these problems for you.

Hey there, thank you so much for the update. Works absolutely fine now, and can also confirm that yes, the gem/diamond placement functionality works perfectly! Love this mod, can't wait to see what other objects you might add to it!

**Comment by FREEDINN3R** [comment]
Yay, glad to hear this!
